# Generated by Django 5.2 on 2025-04-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
