# Generated by Django 5.2 on 2025-04-28 15:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0002_service_is_deleted"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="freelancer",
            new_name="freelancerId",
        ),
    ]
