# Generated by Django 5.2 on 2025-04-28 14:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="client",
            new_name="clientId",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="freelancer",
            new_name="freelancerId",
        ),
    ]
