# Generated by Django 5.2 on 2025-04-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('none', 'None'), ('freelancer', 'Freelancer'), ('client', 'Client')], default='none', help_text='Tracks whether the user is a freelancer, client, or neither.', max_length=10),
        ),
    ]
