# Generated by Django 5.2 on 2025-04-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_customuser_user_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="selfie_verification",
        ),
        migrations.AddField(
            model_name="customuser",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="birth_date",
            field=models.DateField(blank=True, default="2000-01-01"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(blank=True, default="2000-01-01", max_length=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customuser",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="profile_photos/dummy.jpg",
                upload_to="profile_photos/",
            ),
            preserve_default=False,
        ),
    ]
