# Generated by Django 5.2 on 2025-04-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_remove_customuser_selfie_verification_customuser_bio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="address",
            field=models.TextField(blank=True),
        ),
    ]
