# Generated by Django 5.2 on 2025-04-30 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_customuser_photo'),
        ('user', '0005_customuser_address'),
    ]

    operations = [
    ]
