# Generated by Django 5.2 on 2025-05-06 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('experience_level', models.CharField(blank=True, choices=[('junior', 'Junior'), ('mid', 'Mid-Level'), ('senior', 'Senior')], default='junior', help_text='The experience level of the freelancer.', max_length=10, null=True)),
                ('cv', models.URLField(blank=True, help_text="URL to the freelancer's CV.", null=True)),
                ('portfolio', models.URLField(blank=True, help_text="URL to the freelancer's portfolio.", null=True)),
                ('is_tested', models.BooleanField(default=False, help_text='Whether the freelancer has been tested.')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the freelancer is verified.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag for the freelancer.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the freelancer profile was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update to the freelancer profile.')),
                ('skills', models.ManyToManyField(blank=True, help_text='Skills associated with the freelancer.', related_name='freelancers', to='skill.skill')),
            ],
            options={
                'verbose_name': 'Freelancer',
                'verbose_name_plural': 'Freelancers',
                'ordering': ['-created_at'],
            },
        ),
    ]
