# Generated by Django 5.2 on 2025-04-24 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freelancer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Freelancer', 'verbose_name_plural': 'Freelancers'},
        ),
    ]
