# Generated by Django 5.2 on 2025-04-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0002_alter_freelancer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='cv',
            field=models.URLField(blank=True, null=True),
        ),
    ]
