# Generated by Django 5.2 on 2025-04-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0003_alter_freelancer_cv'),
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='freelancers', to='skill.skill'),
        ),
    ]
