# Generated by Django 5.2 on 2025-04-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0004_freelancer_skills'),
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='freelancers', to='skill.skill'),
        ),
    ]
