# Generated by Django 5.2 on 2025-05-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, help_text='Phone number of the client.', max_length=20, null=True)),
                ('company', models.CharField(blank=True, help_text="Name of the client's company.", max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag for the client.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the client profile was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update to the client profile.')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-created_at'],
            },
        ),
    ]
