# Generated by Django 5.2 on 2025-04-30 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('freelancer', '0005_alter_freelancer_skills'),
        ('project', '0003_alter_project_clientid_alter_project_freelancerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Rating value (1 to 5).')),
                ('is_deleted', models.BooleanField(default=False, help_text='Marks whether the rating is deleted.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='The client giving the rating.', on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to='client.client')),
                ('freelancer', models.ForeignKey(help_text='The freelancer being rated.', on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to='freelancer.freelancer')),
                ('project', models.ForeignKey(help_text='The project associated with the rating.', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='project.project')),
            ],
        ),
    ]
